"""PDF forensic report (ReportLab). Every value comes from stored records."""
import hashlib
import statistics
from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

TITLE = "ROCKET FORENSICS"
BANNER = "PROTOTYPE FORENSIC ANALYSIS REPORT"
MAX_TIMELINE_ROWS = 60
LIMITATIONS = [
    "OEM-proprietary DVR/NVR filesystem record parsing is not implemented; standard exported/CCTV containers are supported.",
    "Standard signature carving is available for raw images, but OEM deleted-record reconstruction is not implemented.",
    "Vendor-specific device acquisition protocols are not implemented; acquisition is via evidence-file/image ingestion.",
    "AI detection is general-purpose object/motion detection and requires human validation.",
    "This report does not automatically establish legal admissibility.",
]


def _fmt(v: Any) -> str:
    if v is None:
        return "N/A"
    if isinstance(v, datetime):
        return v.strftime("%Y-%m-%d %H:%M:%S UTC")
    if isinstance(v, float):
        return f"{v:.3f}"
    return str(v)


def detection_summary(events: List[dict]) -> Dict[str, Any]:
    dets = [e for e in events if e.get("event_type") == "object_detection"]
    by_class: Dict[str, List[float]] = {}
    for e in dets:
        by_class.setdefault(e["class_name"], []).append(e["confidence"])
    return {
        "total_detections": len(dets),
        "motion_events": sum(1 for e in events if e.get("event_type") == "motion"),
        "classes": {c: {"count": len(v), "min_conf": min(v), "mean_conf": statistics.fmean(v), "max_conf": max(v)}
                    for c, v in sorted(by_class.items())},
    }


def build_report_pdf(ctx: Dict[str, Any], out_path: Path) -> None:
    """ctx: case, evidence_items[{evidence, devices, events, custody, analysis}], generated_at, generated_by, report_id."""
    ss = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=ss["Title"], fontSize=24, spaceAfter=2)
    h2 = ParagraphStyle("h2", parent=ss["Heading2"], spaceBefore=10, spaceAfter=4)
    body = ParagraphStyle("b", parent=ss["BodyText"], fontSize=9, leading=12)
    cell = ParagraphStyle("c", parent=body, fontSize=8, leading=10)
    mono = ParagraphStyle("m", parent=cell, fontName="Courier", fontSize=7, leading=9)
    banner = ParagraphStyle("bn", parent=body, textColor=colors.HexColor("#b00020"), fontName="Helvetica-Bold",
                            alignment=1, fontSize=11)

    def P(text, style=cell):
        return Paragraph(escape(_fmt(text)), style)

    def table(rows, widths, header=True):
        t = Table(rows, colWidths=widths, repeatRows=1 if header else 0)
        style = [("GRID", (0, 0), (-1, -1), 0.25, colors.grey), ("VALIGN", (0, 0), (-1, -1), "TOP")]
        if header:
            style.append(("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e8e8e8")))
        t.setStyle(TableStyle(style))
        return t

    def kv(pairs, mono_keys=()):
        rows = [[P(k, cell), P(v, mono if k in mono_keys else cell)] for k, v in pairs]
        return table(rows, [42 * mm, 128 * mm], header=False)

    case = ctx["case"]
    story: List[Any] = [
        Paragraph(TITLE, h1), Paragraph("TEAM ROCKET", ParagraphStyle("t", parent=body, alignment=1, fontSize=12)),
        Spacer(1, 6), Paragraph(BANNER, banner),
        Paragraph("Generated by an automated prototype. Results require validation by a qualified examiner "
                  "before any forensic or legal use.", ParagraphStyle("n", parent=body, alignment=1)),
        Spacer(1, 6),
        Paragraph("Report Information", h2),
        kv([("Report ID", ctx["report_id"]), ("Report generation timestamp", ctx["generated_at"]),
            ("Generated by", ctx["generated_by"])]),
        Paragraph("Case Information", h2),
        kv([("Case ID", case["case_id"]), ("Case number", case.get("case_number") or case["case_id"]),
            ("Organization", ctx.get("organization") or "N/A"), ("Name", case["name"]), ("Description", case.get("description") or "N/A"),
            ("Investigator", case["investigator"]), ("Status", case["status"]), ("Created", case["created_at"])]),
    ]

    for i, item in enumerate(ctx["evidence_items"], 1):
        ev, meta = item["evidence"], item["evidence"].get("metadata") or {}
        story += [Paragraph(f"Evidence {i}: {escape(ev['evidence_id'])}", h2), Paragraph("Evidence Information", h2),
                  kv([("Evidence ID", ev["evidence_id"]), ("Original filename", ev["original_filename"]),
                      ("Size (bytes)", ev["file_size"]), ("MIME type (declared)", ev["mime_type"]),
                      ("Camera ID", ev.get("camera_id")), ("Acquired", ev["created_at"]),
                      ("Acquired by", ev["uploaded_by"]),
                      ("Recording start", ev.get("recording_start")),
                      ("Recording start source", ev.get("recording_start_source")),
                      ("Analysis status", ev["analysis_status"])])]

        story.append(Paragraph("Cryptographic Hashes (computed from stored bytes)", h2))
        verif = ("Not verified since acquisition" if ev.get("last_verification_passed") is None else
                 f"{'PASSED' if ev['last_verification_passed'] else 'FAILED'} at {_fmt(ev.get('last_verified_at'))}")
        story.append(kv([("SHA-256", ev["sha256"]), ("MD5", ev["md5"]), ("Hashed at", ev["hashed_at"]),
                         ("Last integrity check", verif)], mono_keys=("SHA-256", "MD5")))

        story.append(Paragraph("Device Information", h2))
        if item["devices"]:
            rows = [[P(x) for x in ("Manufacturer", "Model", "Serial", "Firmware", "Source", "Confidence")]]
            for d in item["devices"]:
                rows.append([P(d["manufacturer"]), P(d.get("model")), P(d.get("serial_number")),
                             P(d.get("firmware")), P(d["source"]), P(d["confidence"])])
            story.append(table(rows, [28 * mm, 28 * mm, 28 * mm, 26 * mm, 32 * mm, 28 * mm]))
            story.append(Paragraph(escape(item["devices"][0].get("confidence_basis") or ""), body))
        else:
            story.append(Paragraph("No device information recorded. Vendor could not be determined from "
                                   "available evidence metadata.", body))

        story.append(Paragraph("File Metadata", h2))
        if meta:
            story.append(kv([(k, meta.get(k)) for k in (
                "format", "duration", "width", "height", "fps", "frame_count", "codec",
                "video_streams", "audio_streams", "creation_time", "extracted_with")]))
        else:
            story.append(Paragraph(f"Metadata unavailable: {escape(str(ev.get('metadata_error')))}", body))

        story.append(Paragraph("AI Detection Summary", h2))
        an = item.get("analysis")
        summ = detection_summary(item["events"])
        if not an:
            story.append(Paragraph("No completed analysis exists for this evidence.", body))
        else:
            o = an["options"]
            story.append(kv([("Analysis ID", an["analysis_id"]), ("Status", an["status"]),
                             ("Model", an.get("model") or "N/A (object detection did not run)"),
                             ("Model version", an.get("model_version") or "N/A"),
                             ("Preset", o.get("preset") or "custom"),
                             ("YOLO device", o.get("yolo_device")),
                             ("Frame sample rate (fps)", o.get("frame_sample_rate")),
                             ("Confidence threshold", o.get("confidence_threshold")),
                             ("Modules", an.get("modules")), ("Warnings", "; ".join(an.get("warnings") or []) or "None"),
                             ("Frames analysed", (an.get("counts") or {}).get("frames_analysed")),
                             ("Total object detections", summ["total_detections"]),
                             ("Motion events", summ["motion_events"])]))
            if summ["classes"]:
                rows = [[P(x) for x in ("Class", "Count", "Min conf.", "Mean conf.", "Max conf.")]]
                for c, s in summ["classes"].items():
                    rows.append([P(c), P(s["count"]), P(s["min_conf"]), P(s["mean_conf"]), P(s["max_conf"])])
                story += [Spacer(1, 4), table(rows, [40 * mm] * 1 + [32 * mm] * 4)]

        story.append(Paragraph("Timeline", h2))
        events = item["events"]
        if events:
            rows = [[P(x) for x in ("Time (UTC)", "Video s", "Frame", "Type", "Class", "Conf.")]]
            for e in events[:MAX_TIMELINE_ROWS]:
                rows.append([P(e["timestamp"]), P(e.get("video_time_seconds")), P(e.get("frame_number")),
                             P(e["event_type"]), P(e.get("class_name")), P(e.get("confidence"))])
            story.append(table(rows, [42 * mm, 20 * mm, 20 * mm, 34 * mm, 28 * mm, 20 * mm]))
            if len(events) > MAX_TIMELINE_ROWS:
                story.append(Paragraph(f"Showing first {MAX_TIMELINE_ROWS} of {len(events)} events.", body))
        else:
            story.append(Paragraph("No timeline events.", body))

        story.append(Paragraph("Chain of Custody", h2))
        rows = [[P(x) for x in ("Timestamp", "Action", "Actor", "Description")]]
        for c in item["custody"]:
            rows.append([P(c["timestamp"]), P(c["action"]), P(c["actor"]), P(c["description"])])
        story.append(table(rows, [38 * mm, 34 * mm, 24 * mm, 74 * mm]))

    story.append(Paragraph("Integrity Statement", h2))
    story.append(Paragraph(
        "This report is generated from the acquired evidence file as stored by the platform and from "
        "cryptographic (SHA-256 / MD5) hashes computed over the actual file bytes at acquisition and "
        "re-computed at verification. Analysis was performed read-only on the stored evidence; annotated "
        "snapshots are separate analysis artifacts. Cross-camera results are temporal correlations only and "
        "do not identify individuals. This is a prototype report and carries no legal certification.", body))
    story.append(Paragraph("Limitations of this Prototype", h2))
    for line in LIMITATIONS:
        story.append(Paragraph("&bull; " + escape(line), body))
    story += [Spacer(1, 8), Paragraph(f"Report generated: {escape(ctx['generated_at'])}", body)]

    def footer(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(colors.grey)
        canvas.drawString(20 * mm, 10 * mm, f"{TITLE} | TEAM ROCKET | {BANNER}")
        canvas.drawRightString(190 * mm, 10 * mm, f"Page {doc.page}")
        canvas.restoreState()

    doc = SimpleDocTemplate(str(out_path), pagesize=A4, leftMargin=20 * mm, rightMargin=20 * mm,
                            topMargin=18 * mm, bottomMargin=18 * mm, title=f"{TITLE} - {case['case_id']}",
                            author="TEAM ROCKET")
    doc.build(story, onFirstPage=footer, onLaterPages=footer)


# ---- DB-facing part -------------------------------------------------------------------
def generate_report(db, case_id: str, evidence_ids: Optional[List[str]], actor: str) -> dict:
    from app.config import get_settings
    from app.database import next_id
    from app.services import case_service, custody_service, evidence_service, timeline_service
    from app.utils.errors import AppError
    from app.utils.mongo import to_api
    from app.utils.timeutil import utcnow

    case = case_service.get_case(db, case_id)
    if evidence_ids:
        docs = [evidence_service.get_evidence_doc(db, e) for e in dict.fromkeys(evidence_ids)]
        if any(d["case_id"] != case_id for d in docs):
            raise AppError(400, "EVIDENCE_CASE_MISMATCH", "One or more evidence items do not belong to this case.")
    else:
        docs = list(db.evidence.find({"case_id": case_id}).sort("created_at", 1))
    if not docs:
        raise AppError(422, "NO_EVIDENCE", "The case has no evidence to report on.")

    now = utcnow()
    report_id = next_id(db, "report", "REPORT-ROCKET", 6)
    items = []
    for d in docs:
        ev = to_api(d)
        analysis = db.analysis_jobs.find_one({"analysis_id": d.get("latest_analysis_id")}) if d.get("latest_analysis_id") else None
        items.append({
            "evidence": ev,
            "devices": [to_api(x) for x in db.devices.find({"evidence_id": d["evidence_id"]})],
            "events": timeline_service.query_events(db, case_id, evidence_id=d["evidence_id"], limit=20000),
            "custody": custody_service.list_records(db, d["evidence_id"]),
            "analysis": to_api(analysis),
        })
    user = db.users.find_one({"user_id": getattr(actor, "user_id", None)}) if getattr(actor, "user_id", None) else None
    ctx = {"case": case, "evidence_items": items, "report_id": report_id,
           "organization": (user or {}).get("organization"),
           "generated_at": now.strftime("%Y-%m-%d %H:%M:%S UTC"), "generated_by": str(actor)}

    s = get_settings()
    s.reports_dir.mkdir(parents=True, exist_ok=True)
    filename = f"{report_id}.pdf"
    path = s.reports_dir / filename
    build_report_pdf(ctx, path)
    data = path.read_bytes()
    doc = {"report_id": report_id, "case_id": case_id, "evidence_ids": [d["evidence_id"] for d in docs],
           "filename": filename, "sha256": hashlib.sha256(data).hexdigest(), "file_size": len(data),
           "generated_at": now, "generated_by": str(actor)}
    db.reports.insert_one(dict(doc))
    for d in docs:
        custody_service.record(db, case_id, d["evidence_id"], "REPORT_GENERATED", actor, d["sha256"],
                               f"Prototype report {report_id} generated (report SHA-256 {doc['sha256']}).")
    return {**doc, "download_url": f"/api/reports/{report_id}/download"}


def get_report(db, report_id: str) -> dict:
    from app.utils.errors import AppError
    doc = db.reports.find_one({"report_id": report_id})
    if not doc:
        raise AppError(404, "REPORT_NOT_FOUND", "Report was not found.")
    from app.utils.mongo import to_api
    return {**to_api(doc), "download_url": f"/api/reports/{report_id}/download"}
