import { useState } from 'react';
import { downloadReport } from '../../api/reports';
import { useToast } from '../../context/ToastContext';
import { fmtDate } from '../../lib/format';
import type { ForensicReport } from '../../types';
import { Button, KV } from '../common/ui';

export default function ReportCard({ r }: { r: ForensicReport }) {
  const toast = useToast();
  const [busy, setBusy] = useState(false);

  return (
    <article className="panel p-4">
      <p className="font-mono text-xs text-ice">
        REPORT-{r.id.slice(-6).toUpperCase()}
      </p>

      <div className="mt-3">
        <KV k="Report ID" v={r.id} mono />
        <KV k="Generated by" v={r.generated_by ?? '—'} />
        <KV k="Generated at" v={fmtDate(r.generated_at)} mono />
        <KV k="Evidence count" v={r.evidence_ids?.length ?? '—'} mono />
        <KV k="SHA-256" v={r.sha256 ?? 'NO DATA AVAILABLE'} mono />
        <KV k="File size" v={r.file_size ?? '—'} mono />
      </div>

      <Button
        className="mt-4"
        busy={busy}
        onClick={async () => {
          setBusy(true);

          try {
            await downloadReport(r.id);
          } catch {
            toast('critical', 'Report download failed');
          } finally {
            setBusy(false);
          }
        }}
      >
        DOWNLOAD PDF
      </Button>
    </article>
  );
}